name: Test

on:
  push:
    branches: [stage, main]
  pull_request:
    branches: [stage]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/stage' && github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Validate dataset
        run: npm run validate
